[package]
name = "engine5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[patch.crates-io]
bevy = { path = "crates/bevy" } 

[dependencies]
bevy = { version = "0.10.1" }
serde = { version = "1.0", features = ["derive"] }
wgpu = "0.16"
log = "0.4"
bevy_prototype_debug_lines = { version = "0.10", features = ["3d"] }
ordered-float = "3.4"
sled = "0.34.7"
anyhow = "1.0.71"
bincode = "1.3.3"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

