[package]
name = "engine5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[patch.crates-io]
bevy = { path = "crates/bevy" } 

[dependencies]
bevy = { version = "0.9.1", features = ["dynamic"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
nalgebra = "0.31"
wgpu = "0.14"
log = "0.4"
bevy_prototype_debug_lines = { version = "0.9", features = ["3d"] }
ordered-float = "3.4"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

